### PR TITLE
Add basic support to monthly recurrence

### PR DESCRIPTION
**Pull request by bruteforcecat**
First, thank you for this great library. I have added monthly as one of the supported frequency. I have to admit that I didn't completely read through the whole codebase so please let me know if there is anything I can improve or have to fix.

### CODE REVIEW

**Comment by doughsay** [comment]
Super cool!  Thanks for the contribution!  I'll have to take a closer look later, but after a quick glance I have one question: Do you support the BYMONTHDAY option?  For example: "FREQ=MONTHLY;INTERVAL=1;BYMONTHDAY=10,15" meaning "monthly on the 10th and 15th"?

**Comment by bruteforcecat** [comment]
It's not supported yet but it should be pretty easy as we were already doing TImex which handle all those marginal cases. I can work later this weekend

**Comment by tfwright** [comment]
I tried out this fork and it looks like it can hang indefinitely in certain cases:

```
iex(1)> Cocktail.Schedule.new(Timex.now |> Timex.shift(months: -6)) |> Cocktail.Schedule.add_recurrence_rule(:monthly, days: [:sunday], interval: 1) |> Cocktail.Schedule.occurrences |> Enum.at(0)
~U[2019-11-03 22:53:45Z]
iex(2)> Cocktail.Schedule.new(Timex.now |> Timex.shift(months: -6)) |> Cocktail.Schedule.add_recurrence_rule(:monthly, days: [:sunday], interval: 2) |> Cocktail.Schedule.occurrences |> Enum.at(0)
~U[2030-03-03 22:53:54Z]
iex(3)> Cocktail.Schedule.new(Timex.now |> Timex.shift(months: -6)) |> Cocktail.Schedule.add_recurrence_rule(:monthly, days: [:sunday], interval: 3) |> Cocktail.Schedule.occurrences |> Enum.at(0)
# hangs forever, CPU spike
```

**Comment by bruteforcecat** [comment]
@tfwright Thank you for reporting this. sorry for the inconvenience. After looking into it, I think I mess up with monthly definition. The current implementation in this PR should be MONTHLY + BYMONTHDAY. I will close this PR for now and hopefully come up with a implementation supporting both MONTHLY and BYMONTHDAY

**Comment by bruteforcecat** [comment]
@tfwright https://github.com/peek-travel/cocktail/pull/111 please check out this

**Comment by tfwright** [comment]
:+1: The problematic rule no longer hangs and returns the expected dates on that branch.

**Pull request closed without merging**
