### PR TITLE
Performance update

### PR DESCRIPTION
**Pull request by doughsay**
TODO:
*   [x] Before and after benchee comparison of various schedules
*   [x] Look into not having to re-run the entire list of validations for a rule just because one validation changed the time.  Some should be trusted to not change it again.
*   [x] Look into using balanced binary tree for list-based validations to reduce the number of checks needed
*   [x] Support parsing and building iCalendar with time of day options

### CODE REVIEW

**Comment by doughsay** [comment]
# Master

```
##### With input bad schedule #####
Name                 ips        average  deviation         median
first 10          151.43        6.60 ms    ±12.55%        6.25 ms
first 100          13.86       72.17 ms     ±5.00%       70.80 ms
first 1000          1.38      723.14 ms     ±1.29%      719.99 ms

Comparison:
first 10          151.43
first 100          13.86 - 10.93x slower
first 1000          1.38 - 109.50x slower

##### With input complex schedule #####
Name                 ips        average  deviation         median
first 10          848.85        1.18 ms     ±9.63%        1.15 ms
first 100          90.44       11.06 ms     ±6.84%       10.85 ms
first 1000          9.14      109.40 ms     ±3.60%      107.73 ms

Comparison:
first 10          848.85
first 100          90.44 - 9.39x slower
first 1000          9.14 - 92.86x slower

##### With input simple schedule #####
Name                 ips        average  deviation         median
first 10         7292.55       0.137 ms    ±12.76%       0.134 ms
first 100         683.72        1.46 ms    ±12.35%        1.41 ms
first 1000         70.71       14.14 ms     ±8.85%       13.66 ms

Comparison:
first 10         7292.55
first 100         683.72 - 10.67x slower
first 1000         70.71 - 103.13x slower
```

# Performance branch

```
##### With input bad schedule #####
Name                 ips        average  deviation         median
first 10          556.34        1.80 ms    ±10.14%        1.74 ms
first 100          47.94       20.86 ms     ±5.87%       20.42 ms
first 1000          4.73      211.53 ms     ±5.94%      207.99 ms

Comparison:
first 10          556.34
first 100          47.94 - 11.61x slower
first 1000          4.73 - 117.68x slower

##### With input complex schedule #####
Name                 ips        average  deviation         median
first 10         12.53 K       79.84 μs    ±14.88%       77.00 μs
first 100         1.32 K      757.14 μs     ±9.60%      736.00 μs
first 1000       0.129 K     7748.55 μs    ±10.35%     7401.50 μs

Comparison:
first 10         12.53 K
first 100         1.32 K - 9.48x slower
first 1000       0.129 K - 97.06x slower

##### With input simple schedule #####
Name                 ips        average  deviation         median
first 10         12.13 K       82.41 μs    ±13.22%       79.00 μs
first 100         1.12 K      893.35 μs    ±10.83%      861.00 μs
first 1000       0.116 K     8630.30 μs    ±10.67%     8231.50 μs

Comparison:
first 10         12.13 K
first 100         1.12 K - 10.84x slower
first 1000       0.116 K - 104.72x slower
```

**Comment by doughsay** [comment]
Discovered truths:
*   All validations for a rule must give a "pass" to the time before it is emitted.
*   When a validation fails, it moves the time to the next time that "passes"
*   If a validation moves the time, all other validations at the same level or above have their "pass" status cleared and must be re-checked.

By following these rules, I can reduce the number of validation checks performed in the loop by a decent amount; should increase performance even more.

**Comment by doughsay** [comment]
# Final comparison

```
##### With input 01 complex schedule #####
Name                 ips        average  deviation         median
first 10         13.57 K       73.67 μs    ±22.25%       70.00 μs
first 100         1.45 K      687.56 μs    ±14.00%      650.00 μs
first 1000       0.146 K     6855.83 μs    ±12.99%     6484.50 μs

Comparison:
first 10         13.57 K
first 100         1.45 K - 9.33x slower
first 1000       0.146 K - 93.06x slower

##### With input 02 simple schedule #####
Name                 ips        average  deviation         median
first 10         12.13 K       82.42 μs    ±15.00%       79.00 μs
first 100         1.14 K      875.77 μs    ±11.12%      847.00 μs
first 1000       0.118 K     8447.83 μs    ±10.41%     8100.50 μs

Comparison:
first 10         12.13 K
first 100         1.14 K - 10.63x slower
first 1000       0.118 K - 102.50x slower

##### With input 03 bad schedule #####
Name                 ips        average  deviation         median
first 10          609.85        1.64 ms    ±10.06%        1.59 ms
first 100          51.56       19.39 ms     ±6.65%       18.85 ms
first 1000          5.09      196.64 ms     ±4.53%      193.57 ms

Comparison:
first 10          609.85
first 100          51.56 - 11.83x slower
first 1000          5.09 - 119.92x slower

##### With input 04 fixed bad schedule #####
Name                 ips        average  deviation         median
first 10         10.13 K       98.73 μs    ±13.13%       96.00 μs
first 100         1.05 K      955.27 μs    ±13.50%      910.00 μs
first 1000       0.105 K     9533.37 μs     ±8.47%     9223.00 μs

Comparison:
first 10         10.13 K
first 100         1.05 K - 9.68x slower
first 1000       0.105 K - 96.56x slower
```

Comparing our "bad schedule" on master to our "fixed bad schedule" on the latest update; getting the first 1000 occurrences:

```
first 1000          1.38      723.14 ms     ±1.29%      719.99 ms
first 1000       0.105 K     9533.37 μs     ±8.47%     9223.00 μs
```

From ~720ms to ~9.2ms; that's a **78.2x improvement.**

**Comment by coladarci** [comment]
bitmoji

**Pull request merged**
